# Generated by Django 4.2.2 on 2023-06-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
